.Dd $Mdocdate: Dec 3 2024$
.Dt NOECHO 1
.Os
.Sh NAME
.Nm noecho
.Nd copy standard input without echoing
.Sh SYNOPSIS
.Nm noecho
.Sh DESCRIPTION
The
.Nm
utility copies the standard input to the standard output without
echoing the standard input to the terminal.
.Sh EXIT STATUS
.Ex -std
.Sh AUTHORS
The
.Nm
utility was written by
.An Henry Ford Aq Mt fordhenry2299@gmail.com
